ssoft2021/applications/sesion/urls.py
#imoport Path
from django.urls import path

from . import views

app_name = 'sesion_app'

urlpatterns = [
    path(
        '', 
        views.HomeView.as_view(), 
        name='home'
    ),
    path(
        'unirse_partida/', 
        views.CrearSalaView.as_view(), 
        name='crear'
    ),
    path( 
        'partida2/', 
        views.iniciar, 
        name='partida2'
    ),
]

ssoft2021/ssoft2021/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    #app home
    re_path('',include('applications.sesion.urls')),
    re_path('', include('applications.cartas.urls')),
    
]

ssoft2021/applications/sesion/models.py
from django.db import models
#import timestampedmodels
from model_utils.models import TimeStampedModel


class Sesion(TimeStampedModel):
    """Modelo para Sesion."""

    sesion = models.CharField(max_length=5)

    class Meta:
        """Meta para Sesion."""
        verbose_name = 'Sesion'
        verbose_name_plural = 'Sesiones'

    def __str__(self):
        """Representacion de Sesion."""
        return str(self.sesion) 

ssoft2021/applications/sesion/forms.py
from django import forms

#import models
from .models import Sesion
from applications.users.models import User


class CreateSalaViewForm(forms.Form):
    """Form para CreateSalaViewForm"""

    class Meta:
        model = Sesion
        fields = 'sesion'

ssoft2021/applications/sesion/views.py
import random
from django.shortcuts import render



#import view.generic
from django.views.generic import FormView, TemplateView

from django.http import HttpResponse

#import forms.forms
from .forms import CreateSalaViewForm
from .models import Sesion
from applications.users.models import User

#Vista de home
class HomeView(TemplateView):
    template_name = "home/home.html"

#vista iniciar aprtida



class CrearSalaView(FormView):
    template_name = "sesion/crear_sala.html"
    form_class = CreateSalaViewForm
    success_url = "sesion/partida1.html"


def iniciar(request):
    
    #captura del nickname
    # nick = request.GET['nick']
    nick = request.GET.get("nick", '')
    #numero de dos digitos aleatorios
    b = random.randint(10, 99)
    #nickname y clavepersonal
    nickname = nick + "-" + str(b)
    
    #nuemero hexadecimal aleatorio
    r = lambda: random.randint(90000,99999)
    r = str('%02X' % (r()))

    #guardado de la sesion en la base de datos
    Sesion.objects.create(sesion=r)
    print(Sesion.objects.all())
    #print(nick)
    print(r)

    User.objects.create(username=nick, activo=True, sesion=(Sesion.objects.last()))
    
    print(nick)
    print(r)

    #return HttpResponse(mensaje)
    return render(request, "cartas/iniciar-partida.html",
    {'nick': nick,
    'r':r})
# 'nick': nick,

ssoft2021/templates/sesion/crear_sala.html
<!-- HTML Base para los templates -->
{% extends 'base.html' %}
{% block title %}El juego SCM{% endblock title %}
{% load static %}
<!-- Bloque en donde se encuentra el template a agregar al Base 
    Crear o unirse a partida
-->
{% block content %}
<<<<<<< HEAD

=======
>>>>>>> b7d2776ba450bb40c224bdbca0ae36a07d4bc6b3
    <!-- Plantilla principal -->
    <div class="container">
        <div class="row justify-content-center text-center pt-4 mt-5 m-1">
            <div class="col-md-6 col-sm-8 col-xl-4 col-lg-5 bg-light">
                <div class="form-group pt-5">
<<<<<<< HEAD
                    <!-- SE puede modificar en este espacio -->
                    <div class="col-12">
                        <h1>Unirse a sala de juegos</h1>
                    </div>
                    <div class="form-floating">
                        <input type="password" class="form-control" id="floatingPassword" placeholder="Password">
                        <label for="floatingPassword">Código de sala</label>
                    </div>
                    <div class="col-12">
                        <a class="btn btn-primary" href="{% url 'sesion_app:home' %}" role="button">Unirse a partida</a>
                    </div>
                    <!-- Obtenido de prueba -->
                    <h1>Crear sala</h1>
                    <form class="form-floating" action="#" method="POST">{% csrf_token %}
                        <div class="form-floating">
                            <input type="text" class="form-control" id="floatingNickname" name="nickname" placeholder="Apodo">
                            <label for="floatingNickname">Nickname</label>
                        </div>
                        <button class="btn btn-primary" type="submit"></button>
                        <!-- <input style="font-size: 26px" type="submit" value="NICKNAME"> -->
                    </form>
                    <!-- FIN DE SE puede modificar en este espacio -->
=======
                    <form action="/unirse_sesion/" method="GET">
                        <div class="col-12">
                            <h1>Unirse a sala de juegos</h1>
                        </div>
                        <div class="form-floating">
                            <input type="text" name="nick2" class="form-control" id="floatingPassword" placeholder="Password">
                            <label for="floatingPassword">Nickname</label>
                        </div>
                        <br>
                        <div class="form-floating">
                            <input type="text" name="cod_sesion" class="form-control" id="floatingPassword" placeholder="Password">
                            <label for="floatingPassword">Código de sala</label>
                        </div>
                        <div class="col-12">
                            <br>

                            
                            <button type="submit" class="btn btn-primary"> Unirse partida</button>
                       
                        </div>
                    </form>
                    _______________________
>>>>>>> b7d2776ba450bb40c224bdbca0ae36a07d4bc6b3
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

<a class="btn btn-primary" href="{% url 'cartas_app:retomar' %}" role="button">Unirse a partida</a>

ssoft2021/templates/sesion/sala-juegos.html
<!-- HTML Base para los templates -->
{% extends 'base.html' %}
{% block title %}Lobby de juego{% endblock title %}
{% load static %}
<!-- Bloque en donde se encuentra el template a agregar al Base 
    Esta es la de iniciador de la partida
-->
{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="x-2 col-5 bg-light border">
                <h1>Columna1</h1>
                <div class="row">
                    <div class="card col" style="width: 18rem;">
                        <img src="../static/img/15.PNG" class="card-img-top" alt="...">
                        <div class="card-body">
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item">Guillermo</li>
                                <li class="list-group-item">Programador</li>
                            </ul>
                        </div>
                    </div>
                    <div class="card col " style="width: 18rem;">
                        <img src="../static/img/2.PNG" class="card-img-top" alt="...">
                        <div class="card-body">
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item">Guillermo</li>
                                <li class="list-group-item">Programador</li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="card col" style="width: 18rem;">
                        <img src="../static/img/3.PNG" class="card-img-top" alt="...">
                        <div class="card-body">
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item">Guillermo</li>
                                <li class="list-group-item">Programador</li>
                            </ul>
                        </div>
                    </div>
                    <div class="card col" style="width: 18rem;">
                        <img src="../static/img/4.PNG" class="card-img-top" alt="...">
                        <div class="card-body">
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item">Guillermo</li>
                                <li class="list-group-item">Programador</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col"></div>
            <div class="x-2 col-5 bg-light border">
                <h1>Columna2</h1>
                <table class="table">
                    <thead class="table-dark">
                        <tr>
                            <td>Quién</td>
                            <td>Notas</td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Carlos</td>
                            <td>La tiene J.F. Kennedy</td>
                        </tr>
                        <tr>
                            <td>Carlos</td>
                            <td>La tiene J.F. Kennedy</td>
                        </tr>
                        <tr>
                            <td>Carlos</td>
                            <td>La tiene J.F. Kennedy</td>
                        </tr>
                        <tr>
                            <td>Carlos</td>
                            <td>La tiene J.F. Kennedy</td>
                        </tr>
                    </tbody>
                </table>
                <table class="table">
                    <thead class="table-dark">
                        <tr>
                            <td>Quién</td>
                            <td>Notas</td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Carlos</td>
                            <td>La tiene J.F. Kennedy</td>
                        </tr>
                        <tr>
                            <td>Carlos</td>
                            <td>La tiene J.F. Kennedy</td>
                        </tr>
                        <tr>
                            <td>Carlos</td>
                            <td>La tiene J.F. Kennedy</td>
                        </tr>
                        <tr>
                            <td>Carlos</td>
                            <td>La tiene J.F. Kennedy</td>
                        </tr>
                    </tbody>
                </table>
                <!-- Div de botones -->
                <div class="row">
                    <div class="col"><button class="btn btn-primary">Preguntar</button></div>
                    <div class="col"><button class="btn btn-primary" onclick="abrir_modal_pregunta('{% url  %}')">Acusar</button></div>
                </div>
            </div>
        </div>
    </div><!-- Fin de módulo a copiar -->

    <div class="modal fade" id="modal_pregunta" role="dialog">

    </div>

{% endblock content %}

{% block scripts %}
    <script type="text/javascript">
        function abrir_modal_pregunta(url) {
            $('#modal_pregunta').load(url), function name(params) {
                $(this).modal('show');
            }
        }
    </script>
{% endblock scripts %}
    