ssoft2021/applications/sesion/urls.py
#imoport Path
from django.urls import path

from . import views

app_name = 'sesion_app'

urlpatterns = [
    path(
        '', 
        views.HomeView.as_view(), 
        name='home'
    ),
    path(
        'unirse_partida/', 
        views.CrearSalaView.as_view(), 
        name='crear'
    ),
    path( 
        'partida2/', 
        views.iniciar, 
        name='partida2'
    ),
]

ssoft2021/ssoft2021/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    #app home
    re_path('',include('applications.sesion.urls')),
    re_path('', include('applications.cartas.urls')),
    
]

ssoft2021/templates/home/home.html
<!-- HTML Base para los templates -->
{% extends 'base.html' %}
{% block title %}El juego SCM{% endblock title %}
{% load static %}
<!-- Bloque en donde se encuentra el template a agregar al Base 
    Crear o unirse a partida
-->

{% block content %}
<div class="container">
    <div class="row justify-content-center text-center pt-4 mt-5 m-1">
        <div class="col-md-6 col-sm-8 col-xl-4 col-lg-5 bg-light">
            <div class="form-group pt-5">
                <!-- Pueden modificar desde este punto -->
                <form class="form-floating" action= "/partida2/" method="GET">
                    <h1>El juego SCM</h1>
                    <div class="form-floating">
                        <input id="nickname" type="text" class="form-control" name="nick">
                        <label for="nickname">Nickname</label>
                    </div>
                    <br><br>
                    <div class="col-12">
                        <input class="btn btn-primary" type="submit" value="Crear la partida">
                        <a class="btn btn-primary" href="{% url 'sesion_app:crear' %}" role="button">Unirse a partida</a>
                </div>
                <!-- <div class="col-12">
                    <form action="/partida2/"  method="GET">
                        <div class="form-floating">
                            <input type="text" class="form-control" name="nick" id="floatingNickname" placeholder="Nickname">
                            <label for="floatingNickname">Escriba su nickname</label>
                        </div>
                        <br><br>
                        <div class="col-12">
                            <input class="btn btn-primary" type="submit" value="Crear partida">
                        
                            <a class="btn btn-primary" href="{% url 'sesion_app:crear' %}" role="button">Unirse a partida</a>
                            <br>
                            _________________________________
                        </div>
                    </form>
                </div> -->
            </div>
        </div>
    </div>
</div>
{% endblock content %}